header:
  Content-Type: application/x-www-form-urlencoded
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
apiURL:
  URL: http://zh.rapa.vip
  登录接口URI: /Identity/api/v1/Account/Login